---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Run the python file
      command: python /var/lib/awx/projects/_18__snow_project/Reading_Excel_file.py
